### ISSUE TITLE
Back icon not working

### ISSUE THREAD

**Issue by ezzini** [ren7995/Atria#1]
1- I just installed Atria on XS Max 14.3 Taurine (Was using Boxy 4 before)
2- I 3D touched an icon in the homescreen -> then  "edit layout"
3- I got a slider to edit the number of rows two buttons "X" on the top-right and a back icon on the top-left
4- I assume the back icon lets the user access more settings about the tweak, but unfortunately the button is not working

I can make a screen recording if necessery.

**Comment by Burrit0z** [comment]
This back button resets the current value to default. 

If you want to access the other options, tap the text at the top of the view.

**Comment by ren7995** [comment]
I'm going to be changing the icon for future versions, but that actually makes the currently editing value revert to whatever the default is. Tapping the label at the top middle of the view brings up other settings. Hope this clears things up.
