### ISSUE TITLE
Cannot place widgets in last row when a new row is added

### ISSUE THREAD

**Issue by p2kdev** [ren7995/Atria#1]
If I increase the row number to 7 for example, I am able to place icons in that space. But it’s not possible to place widgets in that space.

**Comment by ren7995** [comment]
If you respring; iOS will refresh the widget placement metrics and allow you to do so

**Comment by p2kdev** [comment]
> If you respring; iOS will refresh the widget placement metrics and allow you to do so

Already tried and doesn’t work.

**Comment by ren7995** [comment]
Hmm, yeah... I was able to reproduce this issue

I plan on taking a look at whatever makes widgets position themselves, hopefully then I'll be able to see what's up and fix this.

**Comment by UInt2048** [comment]
@p2kdev On iOS 14, widgets are 2 spaces tall, perhaps that's your issue?

**Comment by ren7995** [comment]
Issues with widgets should hopefully be mostly resolved in 1.4.0, which brings big changes that allows widgets to be automatically resized to fit the layout.
