### ISSUE TITLE
Return to edit menut

### ISSUE THREAD

**Issue by jatink129** [ren7995/Atria#12]
I'm not sure if this is a glitch or if it was intended like this, but if I pick any option from "edit layout", once I'm done editing that section, I'm brought back to the home screen.
I then have to once again use have to trigger the "edit layout" to bring back the edit menu to pick the next thing.

Gets tedious. Any way to prevent it from doing that? So that once I edit something, I can choose between returning to edit layout menu or dismissing it.

Thank you.

**Comment by ren7995** [comment]
You can click the title at the top of the editor to return to the list of settings. I'm adding a message/tooltip of sorts that explains this
