### ISSUE TITLE
Bottom Inset Does Not Work

### ISSUE THREAD

**Issue by Soliera** [ren7995/Atria#13]
As the title states, the bottom inset function doesn't work. I can move the slider all I want, and nothing happens
![image](https://user-images.githubusercontent.com/72941716/147382570-80d8c1a9-dcc1-4f8c-a7ac-b51857595a67.png)
![image](https://user-images.githubusercontent.com/72941716/147382577-735a5a48-92ba-423e-ae9f-7a8122ce516b.png)
![image](https://user-images.githubusercontent.com/72941716/147382579-b3c6179e-3796-411e-85fe-12131a2abe4f.png)
Am I an idiot or is this working as intended?

**Comment by ren7995** [comment]
If you use floating dock tweak, it will not work. Floating dock modifies the bottom inset. Try again after disabling floating dock tweak
