### ISSUE TITLE
Random resprings to Safe Mode when used with Zenith on XinA15

### ISSUE THREAD

**Issue by derduesentrieb** [ren7995/Atria#16]
Atria works great on iOS 15 using Xina for me. 

However, when used with the Tweak Zenith, there are frequent random resprings to safe mode.

I have ruled out every other cause. The issue went away immediately after uninstalling Zenith. 

- both Atria‘s and Zenith‘s functionality is 100% there
- the resprings happen randomly, not while performing tweak related inputs. It could be while using another app or while the device is asleep.

[Reddit thread about the problem](https://www.reddit.com/r/jailbreak/comments/zx5z0n/question_atria_zenith_random_resprings/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) 

The dev of Zenith sadly doesn’t respond to any requests and Zenith is closed source. So my hope is that you might find something since those are two essential tweaks for many people. I’d even pay to have this fixed. It’s especially frustrating since both tweaks seem to work 100% fine, it’s just something under the hood that caused the resprings.

**FYI: Zenith only works with the tweak „Zenith iOS 14“ fix installed.**

Since Cr4shed doesn’t work on Xina I have only a crash report created by locksim, maybe you can do something with it.

[CrashLog1.txt](https://github.com/ren7995/Atria/files/10333136/CrashLog1.txt)
[CrashLog2.txt](https://github.com/ren7995/Atria/files/10333137/CrashLog2.txt)

Device: iPhone 13 Pro
iOS: 15.1.1

**Comment by ren7995** [comment]
Will be looking into this more

**Comment by ren7995** [comment]
Issue has been fixed in 1.4.0 betas, marking as resolved
