### ISSUE TITLE
%LOCATION% inaccurate

### ISSUE THREAD

**Issue by olivertzeng** [ren7995/Atria#19]

**Comment by ren7995** [comment]
Hello,
The weather (and the location) is based off of whatever the iOS lock screen widget would use rather than your actual location. Most likely, this will be the first location you have in the Weather app.

**Comment by olivertzeng** [comment]
> Hello, The weather (and the location) is based off of whatever the iOS lock screen widget would use rather than your actual location. Most likely, this will be the first location you have in the Weather app.
ok
