### ISSUE TITLE
Default widget size is too large for allotted space within icons

### ISSUE THREAD

**Issue by beeaniebee** [ren7995/Atria#4]
The widget size is much too large to fit neatly within the allotted space in the icon columns.  For the "medium" and "large" sizes, it even overlaps I got the adjacent icons HPP fixes this issue by making widgets take up one extra "icon" in the columns thus allowing more space to fit. It would be nice to be able at least to customize the "amount of icons" the widget takes up in the columns to the preference of what fits/looks best in the individual layout, if possible, if not per widget type, since the "small" ones seem to fit better (although just barely) than the other types.

**Comment by ren7995** [comment]
A widget icon resize feature has been added for this reason, although there are future plans to resize the widgets in the grid too

**Comment by beeaniebee** [comment]
Ah I gotcha. Thanks! Ended up just revamping my layout to look better with the different behavior from HPP and I like it a lot. Good tweak!

**Comment by ren7995** [comment]
At this point I have it working fine, but I need to write Velox compatibility for Velox’s custom widget sizes, which is a bit more complicated
