### ISSUE TITLE
Icon Scale setting shouldn't apply to icons in folders???

### ISSUE THREAD

**Issue by RadsammyT** [ren7995/Atria#4]
![File May 12, 2 21 37 PM](https://user-images.githubusercontent.com/32146976/118025103-71424200-b32d-11eb-8ed7-80351d3430e7.png)
After updating to the latest version of Atria, Icons in folders are more smaller than usual, but this didn't happen with older versions. I use this scale to compact my icons more in the homescreen with the intended exception for folders, but for some reason the icons in folders have this Icon scale setting applied to them???

**Comment by ren7995** [comment]
There will be an option in the next update to enable or disable this behavior
