### ISSUE TITLE
1.1.1 Update issue (icon dock)

### ISSUE THREAD

**Issue by Vanquished79** [ren7995/Atria#6]
So I noticed that when I upgraded to 1.1.1 it breaks the FiveIconDock tweak that I have installed not allowing me to have five icons anymore I also tried removing and installing a different five icon dock tweak and it also doesn’t work on 1.1.1. 

The issue doesn’t exist on 1.1.0

Thanks.

**Comment by ren7995** [comment]
You must set a custom icon limit with Atria in this version. To do so, 3d touch a dock icon and click “edit dock” or do the triple tap gesture, and set icon limit to 5

If you have any questions, let me know

**Comment by Vanquished79** [comment]
I’m not seeing an option in the edit dock section for icon limits

**Comment by ren7995** [comment]
It's called "Columns"

**Comment by Vanquished79** [comment]
Thanks, works as it should now
