### ISSUE TITLE
Widgets disappear after respring

### ISSUE THREAD

**Issue by vpww** [ren7995/Atria#9]
Hello!
Thank you for great tweak.
I have an issue with widgets disappearing after respring
this is how the first page looks before respring
![Image 1](https://user-images.githubusercontent.com/34859751/121155292-57bee800-c850-11eb-9508-4e8aa0e982e0.jpeg)
this is how it looks after respring, two bottom widgets disappear and now there are icons from the second page
![Image-1](https://user-images.githubusercontent.com/34859751/121155299-5988ab80-c850-11eb-9e0d-5486d4a38f2c.jpeg)
here are my tweak prefs
[me.lau.AtriaPrefs.plist.zip](https://github.com/ren7995/Atria/files/6615011/me.lau.AtriaPrefs.plist.zip)

**Comment by ren7995** [comment]
Thanks, I'll take a look

**Comment by ren7995** [comment]
This issue should be resolved in recent versions.
